### ISSUE TITLE
Error: 'value'

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#100]
Steps to reproduce:
- clear your `data/datasets` directory
- create new analytic unit with 'Drops' type

Expected behaviour:
- successful learning

Actual behaviour:
![image](https://user-images.githubusercontent.com/1989898/43325020-41f50232-91be-11e8-8aa3-0c9fb1c12e73.png)

I guess the thing is in async code. Detector runs `fit` method before there is any dataset.

Related logs:
```
Traceback (most recent call last):
  File "/var/www/analytics/analytic_unit_worker.py", line 28, in do_task
    result = await self.do_learn(analytic_unit_id, segments, pattern)
  File "/var/www/analytics/analytic_unit_worker.py", line 50, in do_learn
    last_prediction_time = await model.learn(segments)
  File "/var/www/analytics/detectors/pattern_detector.py", line 63, in learn
    await self.model.fit(dataframe, segments)
  File "/var/www/analytics/detectors/step_detector.py", line 18, in fit
    data = dataframe['value']
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'value'
```

**Comment by rozetko** [comment]
Actually, it's not a bug
It's about a way dataset import works
If you don't have data in a past week - you get nothing
We should change it

**Comment by jonyrock** [comment]
Ok, I think we can return "User error" (not a error we send when something fails)
This error would say that it is something wrong with user input.
