### ISSUE TITLE
Error: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by deniszh** [hastic/hastic-server#179]
Trying to test Hastic with Graphite. Server and panel are on latest version, but during labelling I'm getting error above from server.
![screen shot 2018-09-27 at 15 34 47](https://user-images.githubusercontent.com/1227222/46150125-281c4d00-c26c-11e8-86ea-eebeb64c4c22.png)

Grafana sending `/status?id=UkWAa3fgmF0Xqv9o` to server and getting `{"status":"FAILED","errorMessage":"Cannot read property 'status' of undefined"}` back.

Segment requests `/segments?id=UkWAa3fgmF0Xqv9o&from=...&to..` are visible and Hastic server returns proper data.

Server error logs:
```TypeError: Cannot read property 'status' of null
    at /var/www/server/dist/server.js:125:23893
    at Generator.next (<anonymous>)
    at o (/var/www/server/dist/server.js:125:23067)
    at <anonymous>
TypeError: Cannot read property 'status' of null
    at /var/www/server/dist/server.js:125:23893
    at Generator.next (<anonymous>)
    at o (/var/www/server/dist/server.js:125:23067)
    at <anonymous>```

**Comment by rozetko** [comment]
Hey, @deniszh 
I'll try to reproduce it now and let you know when it would be fixed

**Comment by rozetko** [comment]
@deniszh, did you create new dashboard and analytic unit after panel update? Or added segments to the old one?

**Comment by deniszh** [comment]
I created everything from scratch. Just reproduced it once more.
![screen shot 2018-09-28 at 14 04 29](https://user-images.githubusercontent.com/1227222/46207372-76425680-c327-11e8-86e5-323863d05d1c.png)

**Comment by rozetko** [comment]
Hey, @deniszh! We've managed to reproduce this bug
It's connected to Docker
Trying to fix it now

**Comment by amper43** [comment]
Hey, @deniszh! Now you can run hastic as described in our wiki (https://github.com/hastic/hastic-server/wiki/Docker)

**Comment by jonyrock** [comment]
@amper43 is it fixed? Is there a log of work?

**Comment by deniszh** [comment]
Hm, I'm still getting this error on 0.2.3-alpha release or latest master btw. I'm using latest panel code too.

**Comment by jonyrock** [comment]
@deniszh please let us know if you experience this issue in 0.3.1-beta
