### ISSUE TITLE
Error: Cannot do slice indexing on with these indexers [nan] of

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#206]
![1](https://user-images.githubusercontent.com/5675912/47513071-2bfcb880-d886-11e8-855b-560c4e886d9a.jpg)

**Comment by amper43** [comment]
'Traceback (most recent call last):
  File "/home/jo/extra/hastic-server/analytics/analytic_unit_manager.py",line 35, in handle_analytic_task
    result_payload = await worker.do_learn(payload['segments'], data, payload['cache'])
  File "/home/jo/extra/hastic-server/analytics/analytic_unit_worker.py", line 19, in do_learn
    return await self.detector.train(data, segments, cache)
  File "/home/jo/extra/hastic-server/analytics/detectors/pattern_detector.py", line 40, in train
    new_cache = self.model.fit(dataframe, segments, cache)
  File "/home/jo/extra/hastic-server/analytics/models/model.py", line 34,in fit
    self.do_fit(dataframe, segments)
  File "/home/jo/extra/hastic-server/analytics/models/peak_model.py", line 47, in do_fit
    labeled_peak = data[segment_max_index - self.state['WINDOW_SIZE']: segment_max_index + self.state['WINDOW_SIZE'] + 1]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 642, in __getitem__
    return self._get_with(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 647, in _get_with
    indexer = self.index._convert_slice_indexer(key, kind='getitem')
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 1382, in _convert_slice_indexer
    return slice(self._validate_indexer('slice', key.start, kind),
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 3388, in _validate_indexer
    self._invalid_indexer(form, key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 1519, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.range.RangeIndex'> with these indexers [nan] of <class 'float'>

**Comment by sankerust** [comment]
I was able to reproduce same bug, happens on peaks model.

**Comment by sankerust** [comment]
Same error happens on `troughs` model.

![image](https://user-images.githubusercontent.com/22073083/47584144-0d6bef80-d962-11e8-888c-db1da7bcb4b9.png)

![image](https://user-images.githubusercontent.com/22073083/47584099-eca39a00-d961-11e8-801f-9aac16221bd4.png)

**Comment by jonyrock** [comment]
@VargBurz  Explanation why it happened necessary for closing task.

**Comment by amper43** [comment]
will be fixed by https://github.com/hastic/hastic-server/issues/231
