### ISSUE TITLE
Error: min() arg in an empty sequence

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#207]
![2](https://user-images.githubusercontent.com/5675912/47513298-9c0b3e80-d886-11e8-9af8-943c4c441243.jpg)

**Comment by amper43** [comment]
2018-10-26 16:36:54,265 [Analytics] [ERROR]  handle_analytic_task exception: 'Traceback (most recent call last):
  File "/home/jo/extra/hastic-server/analytics/analytic_unit_manager.py",line 35, in handle_analytic_task
    result_payload = await worker.do_learn(payload['segments'], data, payload['cache'])
  File "/home/jo/extra/hastic-server/analytics/analytic_unit_worker.py", line 19, in do_learn
    return await self.detector.train(data, segments, cache)
  File "/home/jo/extra/hastic-server/analytics/detectors/pattern_detector.py", line 40, in train
    new_cache = self.model.fit(dataframe, segments, cache)
  File "/home/jo/extra/hastic-server/analytics/models/model.py", line 34,in fit
    self.do_fit(dataframe, segments)
  File "/home/jo/extra/hastic-server/analytics/models/jump_model.py", line 50, in do_fit
    min_jump = min(flat_segment_dropna)
ValueError: min() arg is an empty sequence

**Comment by sankerust** [comment]
I was able to reproduce same bug on same `Jumps` model.

**Comment by jonyrock** [comment]
@VargBurz please add comments why it happened in free form. It is necessary for closing task.

**Comment by amper43** [comment]
will be fixed by https://github.com/hastic/hastic-server/issues/231
