### ISSUE TITLE
IndexError: list index out of range if segment has NaN

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#242]
If segment has just 1 NaN - it drops from learning
Should be possible to have at least 5% of NaNs in segment
```
handle_analytic_task exception: 'Traceback (most recent call last):
  File ".\bin\..\analytics\analytic_unit_manager.py", line 35, in handle_analytic_task
    result_payload = await worker.do_learn(payload['segments'], data, payload['cache'])
  File ".\bin\..\analytics\analytic_unit_worker.py", line 19, in do_learn
    return await self.detector.train(data, segments, cache)
  File ".\bin\..\analytics\detectors\pattern_detector.py", line 40, in train
    new_cache = self.model.fit(dataframe, segments, cache)
  File ".\bin\..\analytics\models\model.py", line 34, in fit
    self.do_fit(dataframe, segments)
  File ".\bin\..\analytics\models\peak_model.py", line 57, in do_fit
    labeled_peak = data[self.ipeaks[n] - self.state['WINDOW_SIZE']: self.ipeaks[n] + self.state['WINDOW_SIZE'] + 1]
IndexError: list index out of range
```

**Comment by jonyrock** [comment]
@VargBurz what is the status of this one?

**Comment by VargBurz** [comment]
It will be reworked with 10 percent
