### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#263]
This is what I got:
```
2018-11-25 13:15:40,034 [Analytics] [ERROR]  handle_analytic_task exception: 'Traceback (most recent call last):
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\analytic_unit_manager.py", line 58, in handle_analytic_task
    result_payload = await worker.do_learn(payload['segments'], data, payload['cache'])
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\analytic_unit_worker.py", line 22, in do_learn
    self.executor, self.detector.train, data, segments, cache
  File "C:\Users\gmpot\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\detectors\pattern_detector.py", line 40, in train
    new_cache = self.model.fit(dataframe, segments, cache)
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\models\model.py", line 34, in fit
    self.do_fit(dataframe, segments)
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\models\jump_model.py", line 74, in do_fit
    jump_center = cen_ind[0]
IndexError: list index out of range
'
```

![image](https://user-images.githubusercontent.com/1022757/48978034-a2275180-f0b6-11e8-9108-25143849dde1.png)

![image](https://user-images.githubusercontent.com/1022757/48978038-b3705e00-f0b6-11e8-83aa-426626ce5846.png)

![image](https://user-images.githubusercontent.com/1022757/48978045-d733a400-f0b6-11e8-92f5-7d13fc3bd592.png)

**Comment by jonyrock** [comment]
It was my bug
