### ISSUE TITLE
Not-ending learning

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#264]
I think I am not the only how experienced when you start a "General" learning and it never ends

![image](https://user-images.githubusercontent.com/1022757/48978462-e4ec2800-f0bc-11e8-8a2a-985bbf849e48.png)

**Comment by jonyrock** [comment]
It might be because analytic fails and restarts without restarting learning

**Comment by jonyrock** [comment]
It is not because of restarting. General pattern indeed could hang just with two steps:

* label a big segment
* save
* delete something predicted
* save

**Comment by rozetko** [comment]
```
2018-12-11 12:41:23,076 [Analytics] [ERROR]  handle_analytic_task exception: 'Traceback (most recent call last):
  File "bin/../analytics/analytic_unit_manager.py", line 77, in handle_analytic_task
    result_payload = await self.__handle_analytic_task(task)
  File "bin/../analytics/analytic_unit_manager.py", line 71, in __handle_analytic_task
    return await worker.do_detect(data, payload['cache'])
  File "bin/../analytics/analytic_unit_worker.py", line 34, in do_detect
    return self._detector.detect(data, cache)
  File "bin/../analytics/detectors/pattern_detector.py", line 50, in detect
    detected = self.model.detect(dataframe, cache)
  File "bin/../analytics/models/model.py", line 47, in detect
    ) for x in result]
  File "bin/../analytics/models/model.py", line 47, in <listcomp>
    ) for x in result]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/series.py", line 601, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2477, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 98, in pandas._libs.index.IndexEngine.get_value (pandas/_libs/index.c:4404)
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value (pandas/_libs/index.c:4087)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 759, in pandas._libs.hashtable.Int64HashTable.get_item (pandas/_libs/hashtable.c:14031)
  File "pandas/_libs/hashtable_class_helper.pxi", line 765, in pandas._libs.hashtable.Int64HashTable.get_item (pandas/_libs/hashtable.c:13975)
KeyError: 2794
'
```

**Comment by jonyrock** [comment]
Maybe it is important that General can`t detect anything after labeling

**Comment by rozetko** [comment]
For some reason this error is not reaching panel (analytic unit status is not updated)

**Comment by jonyrock** [comment]
@rozetko error doesn't reach panel cuz python process itself is down

**Comment by jonyrock** [comment]
This issue reveals following sub-issues:
* Analytics should not be down and send message if https://github.com/hastic/hastic-server/issues/264#issuecomment-446190602 occurs
* Error https://github.com/hastic/hastic-server/issues/264#issuecomment-446190602 must not happen
* Status of analyticUnits should be updated after analytics restart

@rozetko we will create this sub-issues later

**Comment by rozetko** [comment]
@jonyrock the 3rd sub-issue is already created btw: https://github.com/hastic/hastic-server/issues/251

**Comment by rozetko** [comment]
I've managed to reproduce the "infinite" learning behavior without analytics failing
Steps to reproduce:
- label something
- save
- label something else
- save
- learning will not end
@VargBurz do you know possible reasons maybe?
