### ISSUE TITLE
KeyError 45058

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#389]
![image](https://user-images.githubusercontent.com/1022757/52214465-bc459300-28a2-11e9-8686-7e98247d27ab.png)

```
2019-02-04 17:28:49,695 [Analytics] [ERROR]  handle_analytic_task Exception: 'Traceback (most recent call last):
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\analytic_unit_manager.py", line 94, in handle_analytic_task
    result_payload = await self.__handle_analytic_task(task)
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\analytic_unit_manager.py", line 88, in __handle_analytic_task
    return await worker.do_detect(data, payload['cache'])
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\analytic_unit_worker.py", line 34, in do_detect
    return self._detector.detect(data, cache)
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\detectors\pattern_detector.py", line 53, in detect
    detected = self.model.detect(dataframe, cache)
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\models\model.py", line 79, in detect
    ) for x in result]
  File "C:\Projects\hastic-server\analytics\bin\..\analytics\models\model.py", line 79, in <listcomp>
    ) for x in result]
  File "C:\Users\gmpot\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\series.py", line 601, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\gmpot\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\indexes\base.py", line 2477, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 98, in pandas._libs.index.IndexEngine.get_value (pandas\_libs\index.c:4404)
  File "pandas\_libs\index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value (pandas\_libs\index.c:4087)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 759, in pandas._libs.hashtable.Int64HashTable.get_item (pandas\_libs\hashtable.c:14031)
  File "pandas\_libs\hashtable_class_helper.pxi", line 765, in pandas._libs.hashtable.Int64HashTable.get_item (pandas\_libs\hashtable.c:13975)
KeyError: 45058
'
```

![image](https://user-images.githubusercontent.com/1022757/52214437-af28a400-28a2-11e9-9af0-f86c13da8b3b.png)

I were just labeling things. It is dev version.

**Comment by sankerust** [comment]
I also got a similar Error: keyError(1919).
After labeling some random patterns in `general` pattern mode this error arises:
![image](https://user-images.githubusercontent.com/22073083/52291809-4f0a2e80-2984-11e9-88d2-0775f95f4e8c.png)
