### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#563]
Add alert on according level of analytics with user friendly message

```
2019-04-12 19:48:24,346 [Analytics] [ERROR]  handle_analytic_task Exception: 'Traceback (most recent call last):
  File "bin/../analytics/analytic_unit_manager.py", line 82, in handle_analytic_task
    result_payload = await self.__handle_analytic_task(task)
  File "bin/../analytics/analytic_unit_manager.py", line 69, in __handle_analytic_task
    return await worker.do_train(payload['segments'], data, payload['cache'])
  File "bin/../analytics/analytic_unit_worker.py", line 41, in do_train
    new_cache: ModelCache = await asyncio.wait_for(self._training_future, timeout = config.LEARNING_TIMEOUT)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "bin/../analytics/detectors/pattern_detector.py", line 49, in train
    new_cache = self.model.fit(dataframe, segments, self.analytic_unit_id, cache)
  File "bin/../analytics/models/model.py", line 77, in fit
    segment = Segment(dataframe, segment_map, self.find_segment_center)
  File "bin/../analytics/models/model.py", line 23, in __init__
    self.center_index = center_finder(dataframe, self.start, self.end)
  File "bin/../analytics/models/drop_model.py", line 38, in find_segment_center
    segment_center_index = utils.find_pattern_center(segment, start, 'drop')
  File "bin/../analytics/utils/common.py", line 346, in find_pattern_center
    segment_median = utils.get_distribution_density(segment_data)[0]
  File "bin/../analytics/utils/common.py", line 316, in get_distribution_density
    pdf = gaussian_kde(segment)
  File "/usr/lib64/python3.6/site-packages/scipy/stats/kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/usr/lib64/python3.6/site-packages/scipy/stats/kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "/usr/lib64/python3.6/site-packages/scipy/stats/kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/usr/lib64/python3.6/site-packages/scipy/linalg/basic.py", line 946, in inv
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/usr/lib64/python3.6/site-packages/scipy/_lib/_util.py", line 238, in _asarray_validated
    a = toarray(a)
  File "/usr/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1233, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
'
```

**Comment by rozetko** [comment]
We can't get distribution density if there are `NaN` values in a segment. We can safely drop them to fix this issue
There is a bigger problem which leads to this one: wrong `NaN`s handling (https://github.com/hastic/hastic-server/issues/584)
