### ISSUE TITLE
ImportError: cannot import name 'isna'

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#59]
Steps to reproduce:
* clone repo
* go to `analytics/`
* `pip3 install -r requirements.txt`
* `python3 server.py`

You would see error:
```
Traceback (most recent call last):
  File "server.py", line 7, in <module>
    from worker import Worker
  File "/mnt/c/Users/rozetko/git/hastic-server/analytics/worker.py", line 2, in <module>
    from anomaly_model import AnomalyModel
  File "/mnt/c/Users/rozetko/git/hastic-server/analytics/anomaly_model.py", line 2, in <module>
    from data_provider import DataProvider
  File "/mnt/c/Users/rozetko/git/hastic-server/analytics/data_provider.py", line 1, in <module>
    import pandas as pd
  File "/home/rozetko/.local/lib/python3.5/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/rozetko/.local/lib/python3.5/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/home/rozetko/.local/lib/python3.5/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/rozetko/.local/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 42, in <module>
    from pandas.core.dtypes.missing import isna, isnull, notna, _maybe_fill
ImportError: cannot import name 'isna'
```

**Comment by rozetko** [comment]
The problem is in `pandas-datareader` missing
More info: https://stackoverflow.com/q/43809620
