### ISSUE TITLE
Certificate verification issue

### ISSUE THREAD

**Issue by faxm0dem** [hastic/hastic-server#692]
Hi,

My Elasticsearch DS is behind https:

![2019-06-05-124051_6400x2160_scrot](https://user-images.githubusercontent.com/112638/58950561-5f45e500-878f-11e9-9a73-334bdd5cd67e.png)

I'm getting the following error in hastic-server's output while clicking on `Detect` in hastic-app:

```
LEARNING started for uHRGD5MwZdfSR4s0
query time range: from Wed Jun 05 2019 02:11:53 GMT+0200 (CEST) to Wed Jun 05 2019 03:51:55 GMT+0200 (CEST)
Data kit: fail while request data: unable to verify the first certificate query url: "/api/datasources/proxy/1/_msearch"
Error: Data kit: fail while request data: unable to verify the first certificate
    at /usr/lib/hastic-server/server/dist/server.js:9:92024
    at next (native)
    at a (/usr/lib/hastic-server/server/dist/server.js:9:87703)
```

**Comment by rozetko** [comment]
Hey, @faxm0dem 
Are your certificates self-signed?

**Comment by faxm0dem** [comment]
they're not. However, is it possible to force a ca-file or does node use the system-wide?

**Comment by faxm0dem** [comment]
I just tried without https on the grafana side, now I'm getting:

```
LEARNING started for zsNwTApkYDwPQbFw
query time range: from Wed Jun 05 2019 01:21:52 GMT+0200 (CEST) to Wed Jun 05 2019 04:41:56 GMT+0200 (CEST)
Data kit: fail while request data: Request failed with status code 406 query url: "/api/datasources/proxy/1/_msearch"
Response:         status: 406,         response data: {"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406},         headers: {"content-length":"97","content-type":"application/json; charset=UTF-8","date":"Wed, 05 Jun 2019 14:18:35 GMT","connection":"close"}

Error: Data kit: fail while request data: Request failed with status code 406
    at /usr/lib/hastic-server/server/dist/server.js:9:92024
    at next (native)
    at a (/usr/lib/hastic-server/server/dist/server.js:9:87703)
```

**Comment by faxm0dem** [comment]
I think you need to force the content-type to application/json.
this became a requirement since ES 6

**Comment by rozetko** [comment]
Thanks, I'll try to test it with ES 6+ and let you know

**Comment by rozetko** [comment]
@faxm0dem 
Thanks a lot for the suggestion. You were right, it solved the 406 issue (https://github.com/hastic/hastic-server/issues/605).
We'll release this fix in `0.3.6-beta` version.

We'll check if certificate problem is still there soon

**Comment by faxm0dem** [comment]
Has this been resolved yet (just saw there was a new release) ?

**Comment by jonyrock** [comment]
@faxm0dem I believe that not yet :( Looks like it should be fixed in the next milestone https://github.com/hastic/hastic-server/milestone/6

**Comment by jonyrock** [comment]
@rozetko will elaborate on this soon. @faxm0dem sorry for being slow

**Comment by faxm0dem** [comment]
no problem, I'm not in a hurry, was just worried this got forgotten :)

**Comment by jonyrock** [comment]
@amper43 please add your ideas how to fix it and where is it in the code

**Comment by jonyrock** [comment]
@faxm0dem what if set "With CA Cert" "On" ?

**Comment by jonyrock** [comment]
The request goes as follow: 
![image](https://user-images.githubusercontent.com/1022757/61189294-032a8680-a694-11e9-812d-252aae94d7fb.png)

So we 1) request Grafana 2) Grafana request elasticsearch

We do we get error @amper43 ?

**Comment by jonyrock** [comment]
@faxm0dem do you get the same error if you query another datasource (which works without https?)

**Comment by amper43** [comment]
@jonyrock 
most likely in first step

**Comment by jonyrock** [comment]
@amper43

**Comment by faxm0dem** [comment]
There are two issues discussed here, the main one being https://github.com/hastic/hastic-server/issues/692#issuecomment-499104521

I think the certification verify issue is on my side.

**Comment by jonyrock** [comment]
@faxm0dem it might be not your on your side. Looks like it is a popular node.js problem: https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs

**Comment by jonyrock** [comment]
@amper43 what is the next step you want to make to push work on this issue forward?

**Comment by aayush27894** [comment]
Has this been resolved?
I am being able to connect to the server successfully. However, clicking the inspect mode button gives the below error. 

![Screen Shot 2020-03-23 at 3 33 21 PM](https://user-images.githubusercontent.com/33992740/77372281-9b4c3580-6d22-11ea-949b-891d9af30059.png)

**Comment by jonyrock** [comment]
@aayush27894 thank you for reporting. this is an dirty bug we still haven't fixed.
I will definitely will try to put priority on this issue and collaborate with you.

Btw, version 0.3.9 is the latest now

**Comment by aayush27894** [comment]
@jonyrock thank you for the quick response. Yes, I will be working with 0.3.9. 
Will this bug be fixed in the next push?

**Comment by jonyrock** [comment]
@aayush27894 can't guarantee that we with it in this week, but I will keep this issue in our internal backlog

**Comment by aayush27894** [comment]
> @aayush27894 can't guarantee that we with it in this week, but I will keep this issue in our internal backlog

Okay, sounds good. Thank you.

**Comment by rozetko** [comment]
We still can't reproduce it. @faxm0dem @aayush27894 please describe how did you create your certificates.

@aayush27894
>Also, in the mean time, is there a workaround that you could suggest?

There is a [workaround](https://stackoverflow.com/a/48960988) but it's **insecure**, it disables TLS. You can try to run hastic-server with `NODE_TLS_REJECT_UNAUTHORIZED` environment variable set to `0`, e.g.:
 `NODE_TLS_REJECT_UNAUTHORIZED=0 node dist/server`

P.S. I didn't test it, can't tell that it definitely works

**Comment by aayush27894** [comment]
@rozetko I did not create a certificate. Why do I need to create one?
In my case the Hastic server is trying to work with the grafana server on the same ip on different ports. 

In case I do, do you think you guide me how to do it?

Thank you so much, the workaround worked for me!

**Comment by rozetko** [comment]
@aayush27894 the problem is that Hastic can't connect to Grafana, it can be something wrong with your Grafana HTTPS certificate. So I'd like to know more about it.
