### ISSUE TITLE
Warp10 support 

### ISSUE THREAD

**Issue by miton18** [hastic/hastic-server#697]
Do you plan to support Warp10 datasource ?
```
Error: Datasources of type ovh-warp10-datasource are not supported currently
    at /opt/hastic/hastic-server-0.3.5-beta/server/dist/server.js:9:92003
    at Generator.next (<anonymous>)
    at a (/opt/hastic/hastic-server-0.3.5-beta/server/dist/server.js:9:87682)
    at <anonymous>
```

**Comment by rozetko** [comment]
Hey @miton18. We don't have plans to support this datasource. 
But you can ping us: ping@hastic.io, 
we have feature prioritization plan for such cases.
