### ISSUE TITLE
Throw error when database large than nedb limit

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#722]
nedb has limit for database size about 1 Gb. after out of limit Hastic got follow error:
```
Server exception:
Error: "toString()" failed
    at stringSlice (buffer.js:560:43)
    at Buffer.toString (buffer.js:633:10)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:506:23)
process exit
```
Hastic should handle case when database large than nedb limit.

**Comment by rozetko** [comment]
https://github.com/louischatriot/nedb/issues/363#issuecomment-176705239
