### ISSUE TITLE
can't find related aggregation id

### ISSUE THREAD

**Issue by faxm0dem** [hastic/hastic-server#736]
When using elasticsearch6 and hastic 0.3.6beta, I'm getting the following error while labeling the data:

```
LEARNING started for tdqP9vy1ORlAtgXI
query time range: from Wed Jul 31 2019 10:42:42 GMT+0200 (CEST) to Wed Jul 31 2019 16:42:42 GMT+0200 (CEST)
can't find related aggregation id. bucketAggs:[{"fake":true,"field":"cfunc","id":"3","settings":{"min_doc_count":1,"order":"asc","orderBy":"_term","size":"0"},"type":"terms"},{"field":"@timestamp","id":"2","settings":{"interval":"auto","min_doc_count":1,"trimEdges":0},"type":"date_histogram"}] aggregationKeys:["3"]
Error: can't find related aggregation id
    at /var/tmp/hastic-server-0.3.6-beta/server/dist/server.js:9:92709
    at next (native)
    at a (/var/tmp/hastic-server-0.3.6-beta/server/dist/server.js:9:87748)
```

**Comment by jonyrock** [comment]
@amper43 please help me there
@faxm0dem it looks like something we are trying in 0.3.7 (which is not released yet)
