### ISSUE TITLE
queering prometheus: max resolution

### ISSUE THREAD

**Issue by jonyrock-back** [hastic/hastic-server#866]
this is what I get when I have very dense hsr and query on a big range:
```
Data kit: fail while request data: Request failed with status code 400 query url: "/api/datasources/proxy/5/api/v1/query_range"
Response:         status: 400,         response data: {"status":"error","errorType":"bad_data","error":"exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)"},         headers: {"access-control-allow-headers":"Accept, Authorization, Content-Type, Origin","access-control-allow-methods":"GET, OPTIONS","access-control-allow-origin":"*","access-control-expose-headers":"Date","content-type":"application/json","date":"Fri, 28 Feb 2020 03:42:04 GMT","server":"nginx/1.15.5 (Ubuntu)","x-frame-options":"deny","content-length":"159","connection":"close"}

Error: Data kit: fail while request data: Request failed with status code 400
    at Object.<anonymous> (/home/corp/temp_projects/hastic/hastic-server/server/dist/server-dev.js:825:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/corp/temp_projects/hastic/hastic-server/server/dist/server-dev.js:245:32)
```

**Comment by jonyrock-back** [comment]
Steps:
* crete a metric in prom
* make a analytic unit with a small-step-hsr
* todo inspect mode
* zoom out 5 times
