### ISSUE TITLE
Datasource time field is not available

### ISSUE THREAD

**Issue by tuapuikia** [hastic/hastic-server#874]
When I use elasticsearch as data source. I get following error,

hastic-server-0 hastic-server LEARNING started for xxxx
hastic-server-0 hastic-server query time range: from Fri Mar 06 2020 07:59:26 GMT+0000 (UTC) to Fri Mar 06 2020 08:59:26 GMT+0000 (UTC)
hastic-server-0 hastic-server Error: datasource time field not found
hastic-server-0 hastic-server     at /var/www/server/dist/server.js:9:165359
hastic-server-0 hastic-server     at Generator.next (<anonymous>)
hastic-server-0 hastic-server     at s (/var/www/server/dist/server.js:9:160447)
hastic-server-0 hastic-server     at <anonymous>

**Comment by rozetko** [comment]
Hey @tuapuikia 

What ElasticSearch version are you using?

Please attach screenshot of your metric with "Hastic Info" tab opened, like this:
![image](https://user-images.githubusercontent.com/1989898/76071067-b25ef980-5fa6-11ea-9f02-3a548c0e93d3.png)
You can blur sensitive info out if it's necessary

**Comment by tuapuikia** [comment]
Hi,
My Elasticsearch version is 7.6.0

![image](https://user-images.githubusercontent.com/7571272/76074309-1fd64e80-5fd6-11ea-88fc-160d82a713b7.png)

**Comment by tuapuikia** [comment]
The error is from datasource library.

https://github.com/CorpGlory/grafana-datasource-kit/blob/772688965bab3fb4df0ed809aabb4129a95de740/src/metrics/elasticsearch_metric.ts#L62

**Comment by tuapuikia** [comment]
It works if i'm using average data instead of count data. I convert some of my data in ES to integer to resolve this.

**Comment by jonyrock-back** [comment]
@tuapuikia good research! 
would you share your original and fixed query to elastic? That would help.
