### ISSUE TITLE
Dataframe doesn`t contain timestamp:

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#912]
![image](https://user-images.githubusercontent.com/1022757/83337523-66c59e80-a2bc-11ea-9835-3cdd591d6e6c.png)

the error
![image](https://user-images.githubusercontent.com/1022757/83337529-76dd7e00-a2bc-11ea-8d30-c731535426ef.png)

info:
![image](https://user-images.githubusercontent.com/1022757/83337533-8e1c6b80-a2bc-11ea-95f6-217c0b44fcb6.png)

**Comment by jonyrock** [comment]
```
Error: ValueError('Dataframe doesn`t contain timestamp: 2020-05-30 19:15:31.575000',)
    at /home/corp/temp_projects/hastic/hastic-server/server/dist/server-dev.js:549:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/corp/temp_projects/hastic/hastic-server/server/dist/server-dev.js:253:32)
```

**Comment by jonyrock** [comment]
![image](https://user-images.githubusercontent.com/1022757/83337639-a9d44180-a2bd-11ea-8abb-be9a6041d7e2.png)
